"""add updated assessments table

Revision ID: 0169dfe1f923
Revises: d3eb8e184fd0
Create Date: 2026-02-19 16:23:57.087544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0169dfe1f923'
down_revision = 'd3eb8e184fd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('assessment_type', sa.String(), nullable=False))
    op.add_column('assessments', sa.Column('weight_percentage', sa.Float(), nullable=False))
    op.add_column('assessments', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.alter_column('assessments', 'due_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('assessments', 'expected_hours')
    op.drop_column('assessments', 'type')
    op.drop_column('assessments', 'status')
    op.drop_column('assessments', 'hours_completed')
    op.drop_column('assessments', 'weight_percent')
    op.drop_column('assessments', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('assessments', sa.Column('weight_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('assessments', sa.Column('hours_completed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('assessments', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('assessments', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('assessments', sa.Column('expected_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('assessments', 'due_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('assessments', 'is_completed')
    op.drop_column('assessments', 'weight_percentage')
    op.drop_column('assessments', 'assessment_type')
    # ### end Alembic commands ###
