"""add courses table

Revision ID: d3eb8e184fd0
Revises: 0489e0942a66
Create Date: 2026-02-19 13:40:25.984041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3eb8e184fd0'
down_revision = '0489e0942a66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_code', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('course_name', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('credits', sa.Float(), nullable=False))
    op.add_column('courses', sa.Column('target_grade', sa.String(), nullable=False))
    op.drop_column('courses', 'created_at')
    op.drop_column('courses', 'name')
    op.drop_column('courses', 'code')
    op.drop_column('courses', 'color')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('courses', 'target_grade')
    op.drop_column('courses', 'credits')
    op.drop_column('courses', 'course_name')
    op.drop_column('courses', 'course_code')
    # ### end Alembic commands ###
